STDB64DOCTST ; Doctest suite for STDB64 — generated from @example tags.
        ; Generated by tools/gen-doctests.py — DO NOT EDIT BY HAND.
        ; Source: dist/stdlib-manifest.json (label @example tags in src/STDB64.m).
        ; Regenerate with `make doctest`.
        ; m-lint: disable-file=M-MOD-020,M-MOD-001,M-MOD-031
        new pass,fail
        do start^STDASSERT(.pass,.fail)
        ;
        do tDoctestDecode(.pass,.fail)
        do tDoctestEncode(.pass,.fail)
        do tDoctestUrldecode(.pass,.fail)
        do tDoctestValid(.pass,.fail)
        ;
        do report^STDASSERT(pass,fail)
        quit
        ;
tDoctestDecode(pass,fail)       ;@TEST "doctest: STDB64.decode"
        do eq^STDASSERT(.pass,.fail,$$decode^STDB64("Zm9vYmFy"),"foobar","doctest: STDB64.decode")
        quit
        ;
tDoctestEncode(pass,fail)       ;@TEST "doctest: STDB64.encode"
        do eq^STDASSERT(.pass,.fail,$$encode^STDB64("foobar"),"Zm9vYmFy","doctest: STDB64.encode")
        quit
        ;
tDoctestUrldecode(pass,fail)    ;@TEST "doctest: STDB64.urldecode"
        do eq^STDASSERT(.pass,.fail,$$urldecode^STDB64("Zg"),"f","doctest: STDB64.urldecode")
        quit
        ;
tDoctestValid(pass,fail)        ;@TEST "doctest: STDB64.valid"
        do eq^STDASSERT(.pass,.fail,$$valid^STDB64("Zg=="),1,"doctest: STDB64.valid")
        quit
        ;
