STDCRYPTODOCTST ; Doctest suite for STDCRYPTO — generated from @example tags.
        ; Generated by tools/gen-doctests.py — DO NOT EDIT BY HAND.
        ; Source: dist/stdlib-manifest.json (label @example tags in src/STDCRYPTO.m).
        ; Regenerate with `make doctest`.
        ; m-lint: disable-file=M-MOD-020,M-MOD-001,M-MOD-031
        new pass,fail
        do start^STDASSERT(.pass,.fail)
        ;
        do tDoctestSha256(.pass,.fail)
        ;
        do report^STDASSERT(pass,fail)
        quit
        ;
tDoctestSha256(pass,fail)       ;@TEST "doctest: STDCRYPTO.sha256"
        do contains^STDASSERT(.pass,.fail,$$sha256^STDCRYPTO("abc"),"ba7816bf","doctest: STDCRYPTO.sha256")
        quit
        ;
