STDDATEDOCTST ; Doctest suite for STDDATE — generated from @example tags.
        ; Generated by tools/gen-doctests.py — DO NOT EDIT BY HAND.
        ; Source: dist/stdlib-manifest.json (label @example tags in src/STDDATE.m).
        ; Regenerate with `make doctest`.
        ; m-lint: disable-file=M-MOD-020,M-MOD-001,M-MOD-031
        new pass,fail
        do start^STDASSERT(.pass,.fail)
        ;
        do tDoctestAdd(.pass,.fail)
        do tDoctestDiff(.pass,.fail)
        do tDoctestFromh(.pass,.fail)
        do tDoctestStrftime(.pass,.fail)
        do tDoctestStrptime(.pass,.fail)
        do tDoctestToh(.pass,.fail)
        ;
        do report^STDASSERT(pass,fail)
        quit
        ;
tDoctestAdd(pass,fail)          ;@TEST "doctest: STDDATE.add"
        do eq^STDASSERT(.pass,.fail,$$add^STDDATE("47117,0","P1DT2H30M"),"47118,9000","doctest: STDDATE.add")
        quit
        ;
tDoctestDiff(pass,fail)         ;@TEST "doctest: STDDATE.diff"
        do eq^STDASSERT(.pass,.fail,$$diff^STDDATE("47117,0","47118,0"),"P1D","doctest: STDDATE.diff")
        quit
        ;
tDoctestFromh(pass,fail)        ;@TEST "doctest: STDDATE.fromh"
        do eq^STDASSERT(.pass,.fail,$$fromh^STDDATE("47117,0"),"1970-01-01T00:00:00","doctest: STDDATE.fromh")
        quit
        ;
tDoctestStrftime(pass,fail)     ;@TEST "doctest: STDDATE.strftime"
        do eq^STDASSERT(.pass,.fail,$$strftime^STDDATE("47117,0","%Y-%m-%d"),"1970-01-01","doctest: STDDATE.strftime")
        quit
        ;
tDoctestStrptime(pass,fail)     ;@TEST "doctest: STDDATE.strptime"
        do eq^STDASSERT(.pass,.fail,$$strptime^STDDATE("1970-01-01","%Y-%m-%d"),"47117,0","doctest: STDDATE.strptime")
        quit
        ;
tDoctestToh(pass,fail)          ;@TEST "doctest: STDDATE.toh"
        do eq^STDASSERT(.pass,.fail,$$toh^STDDATE("1970-01-01"),"47117,0","doctest: STDDATE.toh")
        quit
        ;
