STDFIXDOCTST ; Doctest suite for STDFIX — generated from @example tags.
        ; Generated by tools/gen-doctests.py — DO NOT EDIT BY HAND.
        ; Source: dist/stdlib-manifest.json (label @example tags in src/STDFIX.m).
        ; Regenerate with `make doctest`.
        ; m-lint: disable-file=M-MOD-020,M-MOD-001,M-MOD-031
        new pass,fail
        do start^STDASSERT(.pass,.fail)
        ;
        do tDoctestActive(.pass,.fail)
        ;
        do report^STDASSERT(pass,fail)
        quit
        ;
tDoctestActive(pass,fail)       ;@TEST "doctest: STDFIX.active"
        do eq^STDASSERT(.pass,.fail,$$active^STDFIX(),0,"doctest: STDFIX.active")
        quit
        ;
