STDFMTDOCTST ; Doctest suite for STDFMT — generated from @example tags.
        ; Generated by tools/gen-doctests.py — DO NOT EDIT BY HAND.
        ; Source: dist/stdlib-manifest.json (label @example tags in src/STDFMT.m).
        ; Regenerate with `make doctest`.
        ; m-lint: disable-file=M-MOD-020,M-MOD-001,M-MOD-031
        new pass,fail
        do start^STDASSERT(.pass,.fail)
        ;
        do tDoctestF(.pass,.fail)
        ;
        do report^STDASSERT(pass,fail)
        quit
        ;
tDoctestF(pass,fail)            ;@TEST "doctest: STDFMT.f"
        do eq^STDASSERT(.pass,.fail,$$f^STDFMT("hi {}","world"),"hi world","doctest: STDFMT.f")
        quit
        ;
