STDFSDOCTST ; Doctest suite for STDFS — generated from @example tags.
        ; Generated by tools/gen-doctests.py — DO NOT EDIT BY HAND.
        ; Source: dist/stdlib-manifest.json (label @example tags in src/STDFS.m).
        ; Regenerate with `make doctest`.
        ; m-lint: disable-file=M-MOD-020,M-MOD-001,M-MOD-031
        new pass,fail
        do start^STDASSERT(.pass,.fail)
        ;
        do tDoctestBasename(.pass,.fail)
        do tDoctestDirname(.pass,.fail)
        do tDoctestExists(.pass,.fail)
        do tDoctestJoin(.pass,.fail)
        ;
        do report^STDASSERT(pass,fail)
        quit
        ;
tDoctestBasename(pass,fail)     ;@TEST "doctest: STDFS.basename"
        do eq^STDASSERT(.pass,.fail,$$basename^STDFS("/etc/hosts"),"hosts","doctest: STDFS.basename")
        quit
        ;
tDoctestDirname(pass,fail)      ;@TEST "doctest: STDFS.dirname"
        do eq^STDASSERT(.pass,.fail,$$dirname^STDFS("/etc/hosts"),"/etc","doctest: STDFS.dirname")
        quit
        ;
tDoctestExists(pass,fail)       ;@TEST "doctest: STDFS.exists"
        do eq^STDASSERT(.pass,.fail,$$exists^STDFS("/etc/hosts"),1,"doctest: STDFS.exists")
        quit
        ;
tDoctestJoin(pass,fail)         ;@TEST "doctest: STDFS.join"
        do eq^STDASSERT(.pass,.fail,$$join^STDFS("/a","b"),"/a/b","doctest: STDFS.join")
        quit
        ;
