STDHEXDOCTST ; Doctest suite for STDHEX — generated from @example tags.
        ; Generated by tools/gen-doctests.py — DO NOT EDIT BY HAND.
        ; Source: dist/stdlib-manifest.json (label @example tags in src/STDHEX.m).
        ; Regenerate with `make doctest`.
        ; m-lint: disable-file=M-MOD-020,M-MOD-001,M-MOD-031
        new pass,fail
        do start^STDASSERT(.pass,.fail)
        ;
        do tDoctestEncode(.pass,.fail)
        do tDoctestEncodeu(.pass,.fail)
        do tDoctestValid(.pass,.fail)
        ;
        do report^STDASSERT(pass,fail)
        quit
        ;
tDoctestEncode(pass,fail)       ;@TEST "doctest: STDHEX.encode"
        do eq^STDASSERT(.pass,.fail,$$encode^STDHEX("foo"),"666f6f","doctest: STDHEX.encode")
        quit
        ;
tDoctestEncodeu(pass,fail)      ;@TEST "doctest: STDHEX.encodeu"
        do eq^STDASSERT(.pass,.fail,$$encodeu^STDHEX("foo"),"666F6F","doctest: STDHEX.encodeu")
        quit
        ;
tDoctestValid(pass,fail)        ;@TEST "doctest: STDHEX.valid"
        do eq^STDASSERT(.pass,.fail,$$valid^STDHEX("DeAdBeEf"),1,"doctest: STDHEX.valid")
        quit
        ;
