STDMOCKDOCTST ; Doctest suite for STDMOCK — generated from @example tags.
        ; Generated by tools/gen-doctests.py — DO NOT EDIT BY HAND.
        ; Source: dist/stdlib-manifest.json (label @example tags in src/STDMOCK.m).
        ; Regenerate with `make doctest`.
        ; m-lint: disable-file=M-MOD-020,M-MOD-001,M-MOD-031
        new pass,fail
        do start^STDASSERT(.pass,.fail)
        ;
        do tDoctestCalled(.pass,.fail)
        do tDoctestResolve(.pass,.fail)
        ;
        do report^STDASSERT(pass,fail)
        quit
        ;
tDoctestCalled(pass,fail)       ;@TEST "doctest: STDMOCK.called"
        do eq^STDASSERT(.pass,.fail,$$called^STDMOCK("noSuchTarget^XYZ"),0,"doctest: STDMOCK.called")
        quit
        ;
tDoctestResolve(pass,fail)      ;@TEST "doctest: STDMOCK.resolve"
        do eq^STDASSERT(.pass,.fail,$$resolve^STDMOCK("noSuchTarget^XYZ"),"noSuchTarget^XYZ","doctest: STDMOCK.resolve")
        quit
        ;
