STDMATHDOCTST ; Doctest suite for STDMATH — generated from @example tags.
        ; Generated by tools/gen-doctests.py — DO NOT EDIT BY HAND.
        ; Source: dist/stdlib-manifest.json (label @example tags in src/STDMATH.m).
        ; Regenerate with `make doctest`.
        ; m-lint: disable-file=M-MOD-020,M-MOD-001,M-MOD-031
        new pass,fail
        do start^STDASSERT(.pass,.fail)
        ;
        do tDoctestClamp(.pass,.fail)
        ;
        do report^STDASSERT(pass,fail)
        quit
        ;
tDoctestClamp(pass,fail)        ;@TEST "doctest: STDMATH.clamp"
        do eq^STDASSERT(.pass,.fail,$$clamp^STDMATH(99,0,10),10,"doctest: STDMATH.clamp")
        quit
        ;
