STDSTRDOCTST ; Doctest suite for STDSTR — generated from @example tags.
        ; Generated by tools/gen-doctests.py — DO NOT EDIT BY HAND.
        ; Source: dist/stdlib-manifest.json (label @example tags in src/STDSTR.m).
        ; Regenerate with `make doctest`.
        ; m-lint: disable-file=M-MOD-020,M-MOD-001,M-MOD-031
        new pass,fail
        do start^STDASSERT(.pass,.fail)
        ;
        do tDoctestEndsWith(.pass,.fail)
        do tDoctestPad(.pass,.fail)
        do tDoctestPadLeft(.pass,.fail)
        do tDoctestPadRight(.pass,.fail)
        do tDoctestRepeat(.pass,.fail)
        do tDoctestReplaceAll(.pass,.fail)
        do tDoctestStartsWith(.pass,.fail)
        do tDoctestToLowerASCII(.pass,.fail)
        do tDoctestToUpperASCII(.pass,.fail)
        do tDoctestTrim(.pass,.fail)
        do tDoctestTrimLeft(.pass,.fail)
        do tDoctestTrimRight(.pass,.fail)
        ;
        do report^STDASSERT(pass,fail)
        quit
        ;
tDoctestEndsWith(pass,fail)     ;@TEST "doctest: STDSTR.endsWith"
        do eq^STDASSERT(.pass,.fail,$$endsWith^STDSTR("hello world","world"),1,"doctest: STDSTR.endsWith")
        quit
        ;
tDoctestPad(pass,fail)          ;@TEST "doctest: STDSTR.pad"
        do eq^STDASSERT(.pass,.fail,$$pad^STDSTR("5",3,"0"),"005","doctest: STDSTR.pad")
        quit
        ;
tDoctestPadLeft(pass,fail)      ;@TEST "doctest: STDSTR.padLeft"
        do eq^STDASSERT(.pass,.fail,$$padLeft^STDSTR("ab",6,"-"),"----ab","doctest: STDSTR.padLeft")
        quit
        ;
tDoctestPadRight(pass,fail)     ;@TEST "doctest: STDSTR.padRight"
        do eq^STDASSERT(.pass,.fail,$$padRight^STDSTR("ab",6,"-"),"ab----","doctest: STDSTR.padRight")
        quit
        ;
tDoctestRepeat(pass,fail)       ;@TEST "doctest: STDSTR.repeat"
        do eq^STDASSERT(.pass,.fail,$$repeat^STDSTR("ab",3),"ababab","doctest: STDSTR.repeat")
        quit
        ;
tDoctestReplaceAll(pass,fail)   ;@TEST "doctest: STDSTR.replaceAll"
        do eq^STDASSERT(.pass,.fail,$$replaceAll^STDSTR("a-b-c","-","+"),"a+b+c","doctest: STDSTR.replaceAll")
        quit
        ;
tDoctestStartsWith(pass,fail)   ;@TEST "doctest: STDSTR.startsWith"
        do eq^STDASSERT(.pass,.fail,$$startsWith^STDSTR("hello world","hello"),1,"doctest: STDSTR.startsWith")
        quit
        ;
tDoctestToLowerASCII(pass,fail) ;@TEST "doctest: STDSTR.toLowerASCII"
        do eq^STDASSERT(.pass,.fail,$$toLowerASCII^STDSTR("Hello-World"),"hello-world","doctest: STDSTR.toLowerASCII")
        quit
        ;
tDoctestToUpperASCII(pass,fail) ;@TEST "doctest: STDSTR.toUpperASCII"
        do eq^STDASSERT(.pass,.fail,$$toUpperASCII^STDSTR("Hello-World"),"HELLO-WORLD","doctest: STDSTR.toUpperASCII")
        quit
        ;
tDoctestTrim(pass,fail)         ;@TEST "doctest: STDSTR.trim"
        do eq^STDASSERT(.pass,.fail,$$trim^STDSTR("  hello  "),"hello","doctest: STDSTR.trim")
        quit
        ;
tDoctestTrimLeft(pass,fail)     ;@TEST "doctest: STDSTR.trimLeft"
        do eq^STDASSERT(.pass,.fail,$$trimLeft^STDSTR("  x  "),"x  ","doctest: STDSTR.trimLeft")
        quit
        ;
tDoctestTrimRight(pass,fail)    ;@TEST "doctest: STDSTR.trimRight"
        do eq^STDASSERT(.pass,.fail,$$trimRight^STDSTR("  x  "),"  x","doctest: STDSTR.trimRight")
        quit
        ;
