STDSEMVERDOCTST ; Doctest suite for STDSEMVER — generated from @example tags.
        ; Generated by tools/gen-doctests.py — DO NOT EDIT BY HAND.
        ; Source: dist/stdlib-manifest.json (label @example tags in src/STDSEMVER.m).
        ; Regenerate with `make doctest`.
        ; m-lint: disable-file=M-MOD-020,M-MOD-001,M-MOD-031
        new pass,fail
        do start^STDASSERT(.pass,.fail)
        ;
        do tDoctestBuild(.pass,.fail)
        do tDoctestCompare(.pass,.fail)
        do tDoctestMajor(.pass,.fail)
        do tDoctestMatches(.pass,.fail)
        do tDoctestMinor(.pass,.fail)
        do tDoctestPatch(.pass,.fail)
        do tDoctestPrerelease(.pass,.fail)
        do tDoctestValid(.pass,.fail)
        ;
        do report^STDASSERT(pass,fail)
        quit
        ;
tDoctestBuild(pass,fail)        ;@TEST "doctest: STDSEMVER.build"
        do eq^STDASSERT(.pass,.fail,$$build^STDSEMVER("1.0.0-rc.1+meta"),"meta","doctest: STDSEMVER.build")
        quit
        ;
tDoctestCompare(pass,fail)      ;@TEST "doctest: STDSEMVER.compare"
        do eq^STDASSERT(.pass,.fail,$$compare^STDSEMVER("1.0.0-rc.1","1.0.0"),-1,"doctest: STDSEMVER.compare")
        quit
        ;
tDoctestMajor(pass,fail)        ;@TEST "doctest: STDSEMVER.major"
        do eq^STDASSERT(.pass,.fail,$$major^STDSEMVER("1.2.3"),1,"doctest: STDSEMVER.major")
        quit
        ;
tDoctestMatches(pass,fail)      ;@TEST "doctest: STDSEMVER.matches"
        do eq^STDASSERT(.pass,.fail,$$matches^STDSEMVER("1.5.0","^1.2.3"),1,"doctest: STDSEMVER.matches")
        quit
        ;
tDoctestMinor(pass,fail)        ;@TEST "doctest: STDSEMVER.minor"
        do eq^STDASSERT(.pass,.fail,$$minor^STDSEMVER("1.2.3"),2,"doctest: STDSEMVER.minor")
        quit
        ;
tDoctestPatch(pass,fail)        ;@TEST "doctest: STDSEMVER.patch"
        do eq^STDASSERT(.pass,.fail,$$patch^STDSEMVER("1.2.3"),3,"doctest: STDSEMVER.patch")
        quit
        ;
tDoctestPrerelease(pass,fail)   ;@TEST "doctest: STDSEMVER.prerelease"
        do eq^STDASSERT(.pass,.fail,$$prerelease^STDSEMVER("1.0.0-rc.1+meta"),"rc.1","doctest: STDSEMVER.prerelease")
        quit
        ;
tDoctestValid(pass,fail)        ;@TEST "doctest: STDSEMVER.valid"
        do eq^STDASSERT(.pass,.fail,$$valid^STDSEMVER("1.0.0-rc.1+exp"),1,"doctest: STDSEMVER.valid")
        quit
        ;
