STDTOMLDOCTST ; Doctest suite for STDTOML — generated from @example tags.
        ; Generated by tools/gen-doctests.py — DO NOT EDIT BY HAND.
        ; Source: dist/stdlib-manifest.json (label @example tags in src/STDTOML.m).
        ; Regenerate with `make doctest`.
        ; m-lint: disable-file=M-MOD-020,M-MOD-001,M-MOD-031
        new pass,fail
        do start^STDASSERT(.pass,.fail)
        ;
        do tDoctestValid(.pass,.fail)
        ;
        do report^STDASSERT(pass,fail)
        quit
        ;
tDoctestValid(pass,fail)        ;@TEST "doctest: STDTOML.valid"
        do eq^STDASSERT(.pass,.fail,$$valid^STDTOML("k = 1"),1,"doctest: STDTOML.valid")
        quit
        ;
