STDURLDOCTST ; Doctest suite for STDURL — generated from @example tags.
        ; Generated by tools/gen-doctests.py — DO NOT EDIT BY HAND.
        ; Source: dist/stdlib-manifest.json (label @example tags in src/STDURL.m).
        ; Regenerate with `make doctest`.
        ; m-lint: disable-file=M-MOD-020,M-MOD-001,M-MOD-031
        new pass,fail
        do start^STDASSERT(.pass,.fail)
        ;
        do tDoctestDecode(.pass,.fail)
        do tDoctestEncode(.pass,.fail)
        do tDoctestNormalize(.pass,.fail)
        do tDoctestResolve(.pass,.fail)
        do tDoctestValid(.pass,.fail)
        ;
        do report^STDASSERT(pass,fail)
        quit
        ;
tDoctestDecode(pass,fail)       ;@TEST "doctest: STDURL.decode"
        do eq^STDASSERT(.pass,.fail,$$decode^STDURL("hello%20world"),"hello world","doctest: STDURL.decode")
        quit
        ;
tDoctestEncode(pass,fail)       ;@TEST "doctest: STDURL.encode"
        do eq^STDASSERT(.pass,.fail,$$encode^STDURL("hello world",""),"hello%20world","doctest: STDURL.encode")
        quit
        ;
tDoctestNormalize(pass,fail)    ;@TEST "doctest: STDURL.normalize"
        do eq^STDASSERT(.pass,.fail,$$normalize^STDURL("HTTPS://EX.COM/a/./b"),"https://ex.com/a/b","doctest: STDURL.normalize")
        quit
        ;
tDoctestResolve(pass,fail)      ;@TEST "doctest: STDURL.resolve"
        do eq^STDASSERT(.pass,.fail,$$resolve^STDURL("http://a/b/c/d","../g"),"http://a/b/g","doctest: STDURL.resolve")
        quit
        ;
tDoctestValid(pass,fail)        ;@TEST "doctest: STDURL.valid"
        do eq^STDASSERT(.pass,.fail,$$valid^STDURL("/foo"),1,"doctest: STDURL.valid")
        quit
        ;
