STDUUIDDOCTST ; Doctest suite for STDUUID — generated from @example tags.
        ; Generated by tools/gen-doctests.py — DO NOT EDIT BY HAND.
        ; Source: dist/stdlib-manifest.json (label @example tags in src/STDUUID.m).
        ; Regenerate with `make doctest`.
        ; m-lint: disable-file=M-MOD-020,M-MOD-001,M-MOD-031
        new pass,fail
        do start^STDASSERT(.pass,.fail)
        ;
        do tDoctestVariant(.pass,.fail)
        do tDoctestVersion(.pass,.fail)
        ;
        do report^STDASSERT(pass,fail)
        quit
        ;
tDoctestVariant(pass,fail)      ;@TEST "doctest: STDUUID.variant"
        do eq^STDASSERT(.pass,.fail,$$variant^STDUUID($$v4^STDUUID()),"rfc4122","doctest: STDUUID.variant")
        quit
        ;
tDoctestVersion(pass,fail)      ;@TEST "doctest: STDUUID.version"
        do eq^STDASSERT(.pass,.fail,$$version^STDUUID($$v4^STDUUID()),4,"doctest: STDUUID.version")
        quit
        ;
